from ray.ray_constants import env_integer

NODE_STATS_UPDATE_INTERVAL_SECONDS = env_integer(
    "NODE_STATS_UPDATE_INTERVAL_SECONDS", 5)
# Error & Log
ERROR_INFO_UPDATE_INTERVAL_SECONDS = 5
LOG_INFO_UPDATE_INTERVAL_SECONDS = 5
