name: "ExampleEnvironment"
runtime: "RAY"  # LOCAL, RAY
max_agent_amount: 100
max_inflight_task: 10000  # <=0 for infinity
log_level: 'DEBUG' # DEBUG, INFO, WARNING, ERROR
log_file: '/tmp/ray/ragent/env.log'
