FROM occlum/occlum:0.29.5-ubuntu20.04 as base


FROM python:3.8.13 as python
RUN pip install -i http://mirrors.cloud.aliyuncs.com/pypi/simple/ --trusted-host mirrors.cloud.aliyuncs.com "grpcio>=1.28.1,<=1.43.0" matplotlib numpy pillow && pip install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cpu
RUN pip install -i https://pypi.tuna.tsinghua.edu.cn/simple ray[tune]==1.13.0 psutil && python -c "import ray; obj = ray.put(1); print(ray.get(obj));" && pip uninstall -y ray
COPY secretflow_ray-1.13.0_occlum-cp38-cp38-linux_x86_64.whl .
RUN pip install secretflow_ray-1.13.0_occlum-cp38-cp38-linux_x86_64.whl
RUN rm secretflow_ray-1.13.0_occlum-cp38-cp38-linux_x86_64.whl

FROM base
COPY --from=python / /root/image
# The `ray` script is generated by python setuptools, however, the interpreter's path is generated based on
# the one used for packaging. Need to modify it manully to the path in Occlum.
RUN sed -i 's/#!\/usr\/local\/bin\/python/#!\/bin\/python3.8/g' /root/image/usr/local/bin/ray
RUN occlum new occlum_instance
RUN apt-get update -y && apt-get install -y lsof net-tools pstack
WORKDIR /root/occlum_instance
COPY python-ray.yaml pytorch_ray.py demo.py /tmp/
COPY data /tmp/data
RUN rm -rf image && copy_bom -f /tmp/python-ray.yaml --root image --include-dir /opt/occlum/etc/template
COPY Occlum.custom.json /tmp/Occlum.custom.json
RUN jq -s '.[0] * .[1]' Occlum.json /tmp/Occlum.custom.json > Occlum.new.json && mv Occlum.new.json Occlum.json
RUN occlum build

