// Copyright 2017 The Ray Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#pragma once

namespace ray {

#define EVENT_LABEL_JOB_PIPELINE_SUBMITTED "JOB_PIPELINE_SUBMMITED"

#define EVENT_LABEL_JOB_PIPELINE_RESOURCES_CHECK "JOB_PIPELINE_RESOURCES_CHECK"

#define EVENT_LABEL_JOB_PIPELINE_ADDED "JOB_PIPELINE_ADDED"

#define EVENT_LABEL_JOB_PIPELINE_ENV_PREPARE_START "JOB_PIPELINE_ENV_PREPARE_START"

#define EVENT_LABEL_JOB_ENV_PREPARE_NOT_FINISH "JOB_ENV_PREPARE_NOT_FINISH"

#define EVENT_LABEL_JOB_PIPELINE_ENV_PREPARE_END "JOB_PIPELINE_ENV_PREPARE_END"

#define EVENT_LABEL_JOB_PIPELINE_DRIVER_START "JOB_PIPELINE_DRIVER_START"

#define EVENT_LABEL_JOB_PIPELINE_DRIVER_EXIT "JOB_PIPELINE_DRIVER_EXIT"

#define EVENT_LABEL_JOB_PIPELINE_LONG_RUNNING "JOB_PIPELINE_LONG_RUNNING"

#define EVENT_LABEL_JOB_PIPELINE_FINISHED "JOB_PIPELINE_FINISHED"

#define EVENT_LABEL_PIPELINE "PIPELINE"

#define EVENT_LABEL_PROCESS_EXIT "PROCESS_EXIT"

#define EVENT_LABEL_RELEASE_NODE "RELEASE_NODE"

#define EVENT_LABEL_RAY_CHECK_FAILED "RAY_CHECK_FAILED"

#define EVENT_LABEL_SIGNAL_ACTION_FAILED "SIGNAL_ACTION_FAILED"

#define EVENT_LABEL_AGENT_NOT_REGISTERED "AGENT_NOT_REGISTERED"

#define EVENT_LABEL_AGENT_EXIT "AGENT_EXIT"

#define EVENT_LABEL_KILL_AGENT "KILL_AGENT"

#define EVENT_LABEL_JOB_RESOURCES_ARE_EXHAUSTED "JOB_RESOURCES_ARE_EXHAUSTED"

#define EVENT_LABEL_JOB_FAILED_TO_ALLOCATE_RESOURCE "JOB_FAILED_TO_ALLOCATE_RESOURCES"

#define EVENT_LABEL_GCS_RESTART "GCS_RESTART"

#define EVENT_LABEL_JOB_L1_FO_START "JOB_L1_FO_START"

#define EVENT_LABEL_JOB_L1_FO_END "JOB_L1_FO_END"

#define EVENT_LABEL_ACTOR_SUBMITTED "ACTOR_SUBMITTED"

#define EVENT_LABEL_ACTOR_REGISTRATION_FINISHED "ACTOR_REGISTRATION_FINISHED"

#define EVENT_LABEL_ACTOR_LEASED_FINISHED "ACTOR_LEASED_FINISHED"

#define EVENT_LABEL_ACTOR_CREATION_FINISHED "ACTOR_CREATION_FINISHED"

#define EVENT_LABEL_ACTOR_EXITED "ACTOR_EXITED"

#define EVENT_LABEL_ACTOR_RECONSTRUCTION_START "ACTOR_RECONSTRUCTION_START"

#define EVENT_LABEL_WORKER_START "WORKER_START"

#define EVENT_LABEL_WORKER_EXIT "WORKER_EXIT"

#define EVENT_LABEL_WORKER_REGISTER_TIMEOUT "WORKER_REGISTER_TIMEOUT"

#define EVENT_LABEL_WORKER_PROCESS_TERMINATED "WORKER_PROCESS_TERMINATED"

#define EVENT_LABEL_PLACEMENT_GROUP_REGISTER_SUCCESS "PLACEMENT_GROUP_REGISTER_SUCCESS"

#define EVENT_LABEL_PLACEMENT_GROUP_REGISTER_FAILED "PLACEMENT_GROUP_REGISTER_FAILED"

#define EVENT_LABEL_PLACEMENT_GROUP_SCHEDULE_SUCCESS "PLACEMENT_GROUP_SCHEDULE_SUCCESS"

#define EVENT_LABEL_PLACEMENT_GROUP_SCHEDULE_FAILED "PLACEMENT_GROUP_SCHEDULE_FAILED"

#define EVENT_LABEL_SLOW_PLACEMENT_GROUP_SCHEDULING "SLOW_PLACEMENT_GROUP_SCHEDULING"

#define EVENT_LABEL_PLACEMENT_GROUP_ADD_BUNDLES_SUCCESS \
  "PLACEMENT_GROUP_ADD_BUNDLES_SUCCESS"

#define EVENT_LABEL_PLACEMENT_GROUP_ADD_BUNDLES_FAILED \
  "PLACEMENT_GROUP_ADD_BUNDLES_FAILED"

#define EVENT_LABEL_PLACEMENT_GROUP_REMOVE_BUNDLES_SUCCESS \
  "PLACEMENT_GROUP_REMOVE_BUNDLES_SUCCESS"

#define EVENT_LABEL_PLACEMENT_GROUP_REMOVE_BUNDLES_FAILED \
  "PLACEMENT_GROUP_REMOVE_BUNDLES_FAILED"

#define EVENT_LABEL_UPDATE_JOB_TOTAL_RESOURCES_FAILED "UPDATE_JOB_TOTAL_RESOURCES_FAILED"

#define EVENT_LABEL_SLOW_TASK "SLOW_TASK"

#define EVENT_LABEL_GCS_MAIN_THREAD_BUSY "GCS_MAIN_THREAD_BUSY"

#define EVENT_LABEL_SLOW_ACTOR_SCHEDULING "SLOW_ACTOR_SCHEDULING"

}  // namespace ray
