/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class
 * com_alipay_streaming_runtime_queue_impl_streamingqueue_QueueConsumerImpl */

#ifndef _Included_com_alipay_streaming_runtime_queue_impl_streamingqueue_QueueConsumerImpl
#define _Included_com_alipay_streaming_runtime_queue_impl_streamingqueue_QueueConsumerImpl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_alipay_streaming_runtime_queue_impl_streamingqueue_QueueConsumerImpl
 * Method:    getBundleNative
 * Signature: (JJJJ)Z
 */
JNIEXPORT jboolean JNICALL
Java_com_alipay_streaming_runtime_queue_impl_streamingqueue_QueueConsumerImpl_getBundleNative(
    JNIEnv *, jobject, jlong, jlong, jlong, jlong);

/*
 * Class:     com_alipay_streaming_runtime_queue_impl_streamingqueue_QueueConsumerImpl
 * Method:    getOffsetsInfo
 * Signature: (J)[B
 */
JNIEXPORT jbyteArray JNICALL
Java_com_alipay_streaming_runtime_queue_impl_streamingqueue_QueueConsumerImpl_getOffsetsInfo(
    JNIEnv *, jobject, jlong);

/*
 * Class:     com_alipay_streaming_runtime_queue_impl_streamingqueue_QueueConsumerImpl
 * Method:    clearCheckpointNative
 * Signature: (J[[B[J)V
 */
JNIEXPORT void JNICALL
Java_com_alipay_streaming_runtime_queue_impl_streamingqueue_QueueConsumerImpl_clearCheckpointNative(
    JNIEnv *, jobject, jlong, jobjectArray, jlongArray);

/*
 * Class:     com_alipay_streaming_runtime_queue_impl_streamingqueue_QueueConsumerImpl
 * Method:    hotUpdateConsumerNative
 * Signature:
 * (J[[B[[BLcom/alipay/streaming/runtime/queue/impl/streamingqueue/StreamingQueueInitialParameters;)V
 */
JNIEXPORT void JNICALL
Java_com_alipay_streaming_runtime_queue_impl_streamingqueue_QueueConsumerImpl_hotUpdateConsumerNative(
    JNIEnv *, jobject, jlong, jobjectArray, jobjectArray, jobject);

/*
 * Class:     com_alipay_streaming_runtime_queue_impl_streamingqueue_QueueConsumerImpl
 * Method:    clearPartialCheckpointNative
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL
Java_com_alipay_streaming_runtime_queue_impl_streamingqueue_QueueConsumerImpl_clearPartialCheckpointNative(
    JNIEnv *, jobject, jlong, jlong, jlong);

/*
 * Class:     com_alipay_streaming_runtime_queue_impl_streamingqueue_QueueConsumerImpl
 * Method:    stopConsumerNative
 * Signature: (J)V
 */
JNIEXPORT void JNICALL
Java_com_alipay_streaming_runtime_queue_impl_streamingqueue_QueueConsumerImpl_stopConsumerNative(
    JNIEnv *, jobject, jlong);

/*
 * Class:     com_alipay_streaming_runtime_queue_impl_streamingqueue_QueueConsumerImpl
 * Method:    closeConsumerNative
 * Signature: (J)V
 */
JNIEXPORT void JNICALL
Java_com_alipay_streaming_runtime_queue_impl_streamingqueue_QueueConsumerImpl_closeConsumerNative(
    JNIEnv *, jobject, jlong);

/*
 * Class:     com_alipay_streaming_runtime_queue_impl_streamingqueue_QueueConsumerImpl
 * Method:    rescaleRollbackNative
 * Signature: (J)V
 */
JNIEXPORT void JNICALL
Java_com_alipay_streaming_runtime_queue_impl_streamingqueue_QueueConsumerImpl_rescaleRollbackNative(
    JNIEnv *, jobject, jlong);

/*
 * Class:     com_alipay_streaming_runtime_queue_impl_streamingqueue_QueueConsumerImpl
 * Method:    newConsumer
 * Signature:
 * (Lcom/alipay/streaming/runtime/queue/impl/streamingqueue/StreamingQueueInitialParameters;[[B[JJLjava/util/List;[B)J
 */
JNIEXPORT jlong JNICALL
Java_com_alipay_streaming_runtime_queue_impl_streamingqueue_QueueConsumerImpl_newConsumer(
    JNIEnv *, jobject, jobject, jobjectArray, jlongArray, jlong, jobject, jbyteArray);

/*
 * Class:     com_alipay_streaming_runtime_queue_impl_streamingqueue_QueueConsumerImpl
 * Method:    onReaderMessageNative
 * Signature: (JJIJIJI)V
 */
JNIEXPORT void JNICALL
Java_com_alipay_streaming_runtime_queue_impl_streamingqueue_QueueConsumerImpl_onReaderMessageNative(
    JNIEnv *, jobject, jlong, jlong, jint, jlong, jint, jlong, jint);

/*
 * Class:     com_alipay_streaming_runtime_queue_impl_streamingqueue_QueueConsumerImpl
 * Method:    onReaderMessageSyncNative
 * Signature: (JJI)[B
 */
JNIEXPORT jbyteArray JNICALL
Java_com_alipay_streaming_runtime_queue_impl_streamingqueue_QueueConsumerImpl_onReaderMessageSyncNative(
    JNIEnv *, jobject, jlong, jlong, jint);

/*
 * Class:     com_alipay_streaming_runtime_queue_impl_streamingqueue_QueueConsumerImpl
 * Method:    getConsumerProfilingInfoNative
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL
Java_com_alipay_streaming_runtime_queue_impl_streamingqueue_QueueConsumerImpl_getConsumerProfilingInfoNative(
    JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
