/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class
 * com_alipay_streaming_runtime_queue_impl_streamingqueue_QueueProducerImpl */

#ifndef _Included_com_alipay_streaming_runtime_queue_impl_streamingqueue_QueueProducerImpl
#define _Included_com_alipay_streaming_runtime_queue_impl_streamingqueue_QueueProducerImpl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_alipay_streaming_runtime_queue_impl_streamingqueue_QueueProducerImpl
 * Method:    getOutputSeqIdNative
 * Signature: (J[[B)[J
 */
JNIEXPORT jlongArray JNICALL
Java_com_alipay_streaming_runtime_queue_impl_streamingqueue_QueueProducerImpl_getOutputSeqIdNative(
    JNIEnv *, jobject, jlong, jobjectArray);

/*
 * Class:     com_alipay_streaming_runtime_queue_impl_streamingqueue_QueueProducerImpl
 * Method:    getBackPressureRatioNative
 * Signature: (J[[B)[D
 */
JNIEXPORT jdoubleArray JNICALL
Java_com_alipay_streaming_runtime_queue_impl_streamingqueue_QueueProducerImpl_getBackPressureRatioNative(
    JNIEnv *, jobject, jlong, jobjectArray);

/*
 * Class:     com_alipay_streaming_runtime_queue_impl_streamingqueue_QueueProducerImpl
 * Method:    broadcastBarrierNative
 * Signature: (JJJ[B)V
 */
JNIEXPORT void JNICALL
Java_com_alipay_streaming_runtime_queue_impl_streamingqueue_QueueProducerImpl_broadcastBarrierNative(
    JNIEnv *, jobject, jlong, jlong, jlong, jbyteArray);

/*
 * Class:     com_alipay_streaming_runtime_queue_impl_streamingqueue_QueueProducerImpl
 * Method:    broadcastUDCMsgNative
 * Signature: (JJ[B)V
 */
JNIEXPORT void JNICALL
Java_com_alipay_streaming_runtime_queue_impl_streamingqueue_QueueProducerImpl_broadcastUDCMsgNative(
    JNIEnv *, jobject, jlong, jlong, jbyteArray);

/*
 * Class:     com_alipay_streaming_runtime_queue_impl_streamingqueue_QueueProducerImpl
 * Method:    getBufferNative
 * Signature: (JJJJ)V
 */
JNIEXPORT void JNICALL
Java_com_alipay_streaming_runtime_queue_impl_streamingqueue_QueueProducerImpl_getBufferNative(
    JNIEnv *, jobject, jlong, jlong, jlong, jlong);

/*
 * Class:     com_alipay_streaming_runtime_queue_impl_streamingqueue_QueueProducerImpl
 * Method:    writeMessageNative
 * Signature: (JJJI)J
 */
JNIEXPORT jlong JNICALL
Java_com_alipay_streaming_runtime_queue_impl_streamingqueue_QueueProducerImpl_writeMessageNative(
    JNIEnv *, jobject, jlong, jlong, jlong, jint);

/*
 * Class:     com_alipay_streaming_runtime_queue_impl_streamingqueue_QueueProducerImpl
 * Method:    stopProducerNative
 * Signature: (J)V
 */
JNIEXPORT void JNICALL
Java_com_alipay_streaming_runtime_queue_impl_streamingqueue_QueueProducerImpl_stopProducerNative(
    JNIEnv *, jobject, jlong);

/*
 * Class:     com_alipay_streaming_runtime_queue_impl_streamingqueue_QueueProducerImpl
 * Method:    closeProducerNative
 * Signature: (J)V
 */
JNIEXPORT void JNICALL
Java_com_alipay_streaming_runtime_queue_impl_streamingqueue_QueueProducerImpl_closeProducerNative(
    JNIEnv *, jobject, jlong);

/*
 * Class:     com_alipay_streaming_runtime_queue_impl_streamingqueue_QueueProducerImpl
 * Method:    clearCheckpointNative
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL
Java_com_alipay_streaming_runtime_queue_impl_streamingqueue_QueueProducerImpl_clearCheckpointNative(
    JNIEnv *, jobject, jlong, jlong, jlong);

/*
 * Class:     com_alipay_streaming_runtime_queue_impl_streamingqueue_QueueProducerImpl
 * Method:    hotUpdateProducerNative
 * Signature:
 * (J[[B[[BLcom/alipay/streaming/runtime/queue/impl/streamingqueue/StreamingQueueInitialParameters;)V
 */
JNIEXPORT void JNICALL
Java_com_alipay_streaming_runtime_queue_impl_streamingqueue_QueueProducerImpl_hotUpdateProducerNative(
    JNIEnv *, jobject, jlong, jobjectArray, jobjectArray, jobject);

/*
 * Class:     com_alipay_streaming_runtime_queue_impl_streamingqueue_QueueProducerImpl
 * Method:    broadcastPartialBarrierNative
 * Signature: (JJJ[B)V
 */
JNIEXPORT void JNICALL
Java_com_alipay_streaming_runtime_queue_impl_streamingqueue_QueueProducerImpl_broadcastPartialBarrierNative(
    JNIEnv *, jobject, jlong, jlong, jlong, jbyteArray);

/*
 * Class:     com_alipay_streaming_runtime_queue_impl_streamingqueue_QueueProducerImpl
 * Method:    clearPartialCheckpointNative
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL
Java_com_alipay_streaming_runtime_queue_impl_streamingqueue_QueueProducerImpl_clearPartialCheckpointNative(
    JNIEnv *, jobject, jlong, jlong, jlong);

/*
 * Class:     com_alipay_streaming_runtime_queue_impl_streamingqueue_QueueProducerImpl
 * Method:    rescaleRollbackNative
 * Signature: (J)V
 */
JNIEXPORT void JNICALL
Java_com_alipay_streaming_runtime_queue_impl_streamingqueue_QueueProducerImpl_rescaleRollbackNative(
    JNIEnv *, jobject, jlong);

/*
 * Class:     com_alipay_streaming_runtime_queue_impl_streamingqueue_QueueProducerImpl
 * Method:    newProducer
 * Signature:
 * (Lcom/alipay/streaming/runtime/queue/impl/streamingqueue/StreamingQueueInitialParameters;[[B[JJ[B)J
 */
JNIEXPORT jlong JNICALL
Java_com_alipay_streaming_runtime_queue_impl_streamingqueue_QueueProducerImpl_newProducer(
    JNIEnv *, jobject, jobject, jobjectArray, jlongArray, jlong, jbyteArray);

/*
 * Class:     com_alipay_streaming_runtime_queue_impl_streamingqueue_QueueProducerImpl
 * Method:    onWriterMessageNative
 * Signature: (JJI)V
 */
JNIEXPORT void JNICALL
Java_com_alipay_streaming_runtime_queue_impl_streamingqueue_QueueProducerImpl_onWriterMessageNative(
    JNIEnv *, jobject, jlong, jlong, jint);

/*
 * Class:     com_alipay_streaming_runtime_queue_impl_streamingqueue_QueueProducerImpl
 * Method:    onWriterMessageSyncNative
 * Signature: (JJI)[B
 */
JNIEXPORT jbyteArray JNICALL
Java_com_alipay_streaming_runtime_queue_impl_streamingqueue_QueueProducerImpl_onWriterMessageSyncNative(
    JNIEnv *, jobject, jlong, jlong, jint);

/*
 * Class:     com_alipay_streaming_runtime_queue_impl_streamingqueue_QueueProducerImpl
 * Method:    broadcastEndOfDataBarrierNative
 * Signature: (J)V
 */
JNIEXPORT void JNICALL
Java_com_alipay_streaming_runtime_queue_impl_streamingqueue_QueueProducerImpl_broadcastEndOfDataBarrierNative(
    JNIEnv *, jobject, jlong);

/*
 * Class:     com_alipay_streaming_runtime_queue_impl_streamingqueue_QueueProducerImpl
 * Method:    getProducerProfilingInfoNative
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL
Java_com_alipay_streaming_runtime_queue_impl_streamingqueue_QueueProducerImpl_getProducerProfilingInfoNative(
    JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
