# Auto-generate a Pull Request to merge from master to main branch daily
# Author: mingcheng <mingcheng@apache.org>

name: Auto Create Merge PR

on:
  schedule:
    - cron: '0 1 * * *'

  workflow_dispatch:
    inputs:
      source_branch:
        description: 'Source branch to merge from'
        required: true
        default: 'master'
        type: string
      target_branch:
        description: 'Target branch to merge into'
        required: true
        default: 'main'
        type: string
      assignees:
        description: 'Assignees for the PR'
        required: false
        default: 'mingcheng'
        type: string

jobs:
  create-merge-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_TOKEN }}
          fetch-depth: 0
      - name: Reset promotion branch
        run: |
          git fetch origin ${{ github.event.inputs.source_branch || 'master' }}:${{ github.event.inputs.source_branch || 'master' }}
          git reset --hard ${{ github.event.inputs.source_branch || 'master' }}
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GH_TOKEN }}
          # branch: ${{ github.event.inputs.source_branch || 'master' }}
          base: ${{ github.event.inputs.target_branch || 'main' }}
          title: '🔄 Daily merge: upstream master branch to main ($(date +%Y-%m-%d))'
          body: |
            ## This is auto-generated Merge Pull Request

            This PR is created automatically by a GitHub Action to merge the latest changes from the upstream `master` branch into the `main` branch.

            📅 **Created**: $(date +%Y-%m-%d)
            🔀 **Merge direction**: upstream ${{ github.event.inputs.source_branch || 'master' }} → ${{ github.event.inputs.target_branch || 'main' }}
            🤖 **Trigger by**: ${{ github.event_name == 'workflow_dispatch' && 'Manual' || 'Scheduled' }}

            Please review before merging. This PR is Auto-generated by [create-pull-request][1] GitHub Action.
            [1]: https://github.com/peter-evans/create-pull-request
          labels: |
            automated
            merge
          draft: false
          branch-suffix: short-commit-hash
          delete-branch: true
          assignees: ${{ github.event.inputs.assignees || 'mingcheng' }}
