name: Deploy Documentation

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      branch:
        description: 'Enter branch name to deploy from (default: main)'
        required: false
        type: string
        default: 'main'

jobs:
  deploy-docs:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: doc
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch || 'main' }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Sphinx and dependencies
        run: |
          sudo apt-get install python3-sphinx
          pip install -r requirements-doc.txt
          pip install aiohttp_cors

      - name: Build documentation
        run: make develop

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: doc/_build/html/
          keep_files: false