name: Ant Ray PyPi Nightly

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
  release:
    types:
      - published

jobs:
  build_wheels_on_linux:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # macos-13 is an intel runner, macos-14 is apple silicon
        # os: [ubuntu-latest, windows-latest, macos-13, macos-14]
        os: [ubuntu-22.04]

    steps:
      - uses: actions/checkout@v4

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.22.0
        env:
          CIBW_BEFORE_BUILD: pip install "cython>=0.29.32" wheel && ./ci/env/install-bazel.sh --system
          CIBW_BUILD: |
            cp39-manylinux_aarch64
            cp39-musllinux_x86_64

          CIBW_ENVIRONMENT: RAY_DEBUG_BUILD=nightly SKIP_THIRDPARTY_INSTALL=1
        with:
          package-dir: ./python
          output-dir: ./python/dist

      - uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
          path: ./python/dist/*.whl

  build_wheels_on_macos:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # macos-13 is an intel runner, macos-14 is apple silicon
        # os: [ubuntu-latest, windows-latest, macos-13, macos-14]
        os: [macos-13]

    steps:
      - uses: actions/checkout@v4

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.22.0
        env:
          CIBW_BEFORE_BUILD: pip install "cython>=0.29.32" wheel && ./ci/env/install-bazel.sh --system
          CIBW_BUILD: cp39-macosx_*

          CIBW_ENVIRONMENT: RAY_DEBUG_BUILD=nightly
        with:
          package-dir: ./python
          output-dir: ./python/dist

      - uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
          path: ./python/dist/*.whl

  build_wheels_on_macos_silicon:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # macos-13 is an intel runner, macos-14 is apple silicon
        # os: [ubuntu-latest, windows-latest, macos-13, macos-14]
        os: [macos-14]

    steps:
      - uses: actions/checkout@v4

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.22.0
        env:
          CIBW_BEFORE_BUILD: pip install "cython>=0.29.32" wheel && ./ci/env/install-bazel.sh --system
          CIBW_BUILD: cp39-macosx_*

          CIBW_ENVIRONMENT: RAY_DEBUG_BUILD=nightly
        with:
          package-dir: ./python
          output-dir: ./python/dist

      - uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
          path: ./python/dist/*.whl