name: Ant Ray PyPi Nightly

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
  # pull_request:
  # push:
  #   branches:
  #     - main
  release:
    types:
      - published

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # macos-13 is an intel runner, macos-14 is apple silicon
        # os: [ubuntu-latest, windows-latest, macos-13, macos-14]
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.22.0
        env:
          CIBW_BEFORE_BUILD_LINUX: yum -y update && yum -y install npm && pip install "cython>=0.29.32" wheel && ./ci/env/install-bazel.sh && pushd python/ray/dashboard/client && npm ci && npm run build && popd
          CIBW_BUILD: cp39-manylinux_x86_64
          CIBW_ENVIRONMENT: RAY_DEBUG_BUILD=nightly
        with:
          package-dir: ./python
          output-dir: ./python/dist

      - name: Build doc
        run: |
          pushd doc
          pip install -r requirements-doc.txt
          make develop

      - uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
          path: ./python/dist/*.whl

      - name: upload doc
        uses: actions/upload-artifact@v4
        with:
          name: doc-html-${{ strategy.job-index }}
          path: ./doc/_build/html

      - name: notify to download artifacts
        run: echo ${{steps.upload_doc.outputs.artifact_url}}