name: Ant Ray PyPi Release(macos)

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Enter branch name to build from (default: main)'
        required: false
        type: string
        default: 'main'

  release:
    types:
      - published

jobs:
  build_wheels_on_macos:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # macos-13 is an intel runner, macos-14 is apple silicon
        # os: [ubuntu-latest, windows-latest, macos-13, macos-14]
        os: [macos-13]

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch || 'main' }}

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.22.0
        env:
          CIBW_BEFORE_BUILD: pip install "cython>=0.29.32" wheel && sudo ./ci/env/install-bazel.sh && python -m ensurepip --upgrade && sudo chmod a+x /Users/runner/bin/bazel && sudo chown -R runner /Users/runner/Library/Caches/bazelisk
          CIBW_BUILD: |
            cp39-macosx_*
            cp310-macosx_*
            cp311-macosx_*
        with:
          package-dir: ./python
          output-dir: ./python/dist

      - uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
          path: ./python/dist/*.whl

  build_wheels_on_macos_silicon:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # macos-13 is an intel runner, macos-14 is apple silicon
        # os: [ubuntu-latest, windows-latest, macos-13, macos-14]
        os: [macos-14]

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch || 'main' }}

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.22.0
        env:
          CIBW_BEFORE_BUILD: pip install "cython>=0.29.32" wheel && sudo ./ci/env/install-bazel.sh && python -m ensurepip --upgrade && sudo chmod a+x /Users/runner/bin/bazel && sudo chown -R runner /Users/runner/Library/Caches/bazelisk
          CIBW_BUILD: |
            cp39-macosx_*
            cp310-macosx_*
            cp311-macosx_*
        with:
          package-dir: ./python
          output-dir: ./python/dist

      - uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
          path: ./python/dist/*.whl

  upload_pypi:
    needs: [build_wheels_on_macos, build_wheels_on_macos_silicon]
    runs-on: ubuntu-latest
    environment: pypi
    permissions:
      id-token: write
    # if: github.event_name == 'release' && github.event.action == 'published'
    # # or, alternatively, upload to PyPI on every tag starting with 'v' (remove on: release above to use this)
    # # if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
    steps:
      - uses: actions/download-artifact@v4
        with:
          # unpacks all CIBW artifacts into dist/
          pattern: cibw-*
          path: python/dist
          merge-multiple: true

      - uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: python/dist

  upload_test_pypi:
    needs: [build_wheels_on_macos, build_wheels_on_macos_silicon]
    runs-on: ubuntu-latest
    environment: testpypi-publish
    permissions:
      id-token: write
    steps:
      - uses: actions/download-artifact@v4
        with:
          # unpacks all CIBW artifacts into dist/
          pattern: cibw-*
          path: python/dist
          merge-multiple: true

      - uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: python/dist
          repository-url: https://test.pypi.org/legacy/

