name: CI

on:
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Enter branch name to build wheels from (default: main)'
        required: false
        type: string
        default: 'main'

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch || 'main' }}
      
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          
      - name: Set up environment
        run: |
          sudo apt-get update
          sudo add-apt-repository ppa:ubuntu-toolchain-r/ppa -y
          sudo apt-get install -y build-essential gcc-10 g++-10
          sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-10 100
          sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-10 100
          ./ci/env/install-bazel.sh
          python -m pip install -r python/requirements.txt
          python -m ensurepip

      - name: Run core tests
        run: |
          touch ~/.bashenv
          . ./ci/ci.sh init && source ~/.bashenv
          source ~/.bashrc
          ./ci/ci.sh build
          ./ci/ci.sh test_core
          ./ci/ci.sh test_python

      - name: Run C++ tests
        run: ./ci/ci.sh test_cpp

      - name: Run wheel tests
        run: ./ci/ci.sh test_wheels

      - name: Upload test artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: |
            /tmp/artifacts/test-summaries/*
            /tmp/ray/session_latest/logs/*
